server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://106.52.202.118:3306/Test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update